### ISSUE TITLE
Utilização de Stream nos FindAll

### ISSUE THREAD

**Issue by arthurs159** [BernardoZacaron/Financial-Report-generator#1]
Ei Bernardo, beleza?
Olhando seu projeto, percebo que você utiliza muito o `findAll()` para buscar apenas um elemento, tipo assim:
![image](https://user-images.githubusercontent.com/77133022/212776614-c2d32fde-7f58-4e09-8b98-8f3b5e0c4458.png)

O findAll() utilizamos apenas para buscar alguma lista, o mais correto ao meu ver, seria utilizar o stream do java 8, para fitrar apenas o primeiro logo de cara, falando nisso, é um assunto muito importante para estudar, o que acha da ideia?

O mais correto, seria buscar a carteira pelo `ID`, mas é mais dica mesmo, se quiser tentar : )

Qualquer coisa, se ficar com dúvida, só me pingar lá no discord, beleza?

**Comment by BernardoZacaron** [comment]
Certamente, isso ai foi uma clássica gambiarra xD
Vou corrigir isso assim que possível. Obrigado!
